# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mdb_edit_media_types.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_edit_media_types_window(object):
    def setupUi(self, edit_media_types_window):
        edit_media_types_window.setObjectName("edit_media_types_window")
        edit_media_types_window.setWindowModality(QtCore.Qt.WindowModal)
        edit_media_types_window.resize(400, 480)
        edit_media_types_window.setMinimumSize(QtCore.QSize(400, 480))
        edit_media_types_window.setMaximumSize(QtCore.QSize(500, 800))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        edit_media_types_window.setFont(font)
        self.central_widget = QtWidgets.QWidget(edit_media_types_window)
        self.central_widget.setObjectName("central_widget")
        self.vl_central_widget = QtWidgets.QVBoxLayout(self.central_widget)
        self.vl_central_widget.setObjectName("vl_central_widget")
        self.gb_media_types = QtWidgets.QGroupBox(self.central_widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.gb_media_types.setFont(font)
        self.gb_media_types.setAlignment(QtCore.Qt.AlignCenter)
        self.gb_media_types.setObjectName("gb_media_types")
        self.gridLayout = QtWidgets.QGridLayout(self.gb_media_types)
        self.gridLayout.setObjectName("gridLayout")
        self.le_type_name = QtWidgets.QLineEdit(self.gb_media_types)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.le_type_name.setFont(font)
        self.le_type_name.setObjectName("le_type_name")
        self.gridLayout.addWidget(self.le_type_name, 5, 0, 1, 1)
        self.btn_update_type = QtWidgets.QPushButton(self.gb_media_types)
        self.btn_update_type.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_update_type.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_update_type.setFont(font)
        self.btn_update_type.setObjectName("btn_update_type")
        self.gridLayout.addWidget(self.btn_update_type, 1, 1, 1, 1)
        self.btn_done = QtWidgets.QPushButton(self.gb_media_types)
        self.btn_done.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_done.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_done.setFont(font)
        self.btn_done.setObjectName("btn_done")
        self.gridLayout.addWidget(self.btn_done, 4, 1, 1, 1)
        self.btn_clear = QtWidgets.QPushButton(self.gb_media_types)
        self.btn_clear.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_clear.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout.addWidget(self.btn_clear, 5, 1, 1, 1)
        self.btn_delete_type = QtWidgets.QPushButton(self.gb_media_types)
        self.btn_delete_type.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_delete_type.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_delete_type.setFont(font)
        self.btn_delete_type.setObjectName("btn_delete_type")
        self.gridLayout.addWidget(self.btn_delete_type, 2, 1, 1, 1)
        self.lbl_type_name = QtWidgets.QLabel(self.gb_media_types)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lbl_type_name.setFont(font)
        self.lbl_type_name.setObjectName("lbl_type_name")
        self.gridLayout.addWidget(self.lbl_type_name, 4, 0, 1, 1)
        self.btn_add_type = QtWidgets.QPushButton(self.gb_media_types)
        self.btn_add_type.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_add_type.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn_add_type.setFont(font)
        self.btn_add_type.setObjectName("btn_add_type")
        self.gridLayout.addWidget(self.btn_add_type, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.lst_media_types = QtWidgets.QListWidget(self.gb_media_types)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lst_media_types.setFont(font)
        self.lst_media_types.setObjectName("lst_media_types")
        self.gridLayout.addWidget(self.lst_media_types, 0, 0, 4, 1)
        self.vl_central_widget.addWidget(self.gb_media_types)
        self.vl_central_widget.setStretch(0, 1)
        edit_media_types_window.setCentralWidget(self.central_widget)

        self.retranslateUi(edit_media_types_window)
        QtCore.QMetaObject.connectSlotsByName(edit_media_types_window)

    def retranslateUi(self, edit_media_types_window):
        _translate = QtCore.QCoreApplication.translate
        edit_media_types_window.setWindowTitle(_translate("edit_media_types_window", "Edit Genres"))
        self.gb_media_types.setTitle(_translate("edit_media_types_window", "Media Types"))
        self.le_type_name.setPlaceholderText(_translate("edit_media_types_window", "e.g. Audio CD, DVD, Casset, etc."))
        self.btn_update_type.setText(_translate("edit_media_types_window", "&Update"))
        self.btn_update_type.setShortcut(_translate("edit_media_types_window", "Alt+U"))
        self.btn_done.setText(_translate("edit_media_types_window", "&Done"))
        self.btn_done.setShortcut(_translate("edit_media_types_window", "Esc"))
        self.btn_clear.setText(_translate("edit_media_types_window", "&Clear"))
        self.btn_clear.setShortcut(_translate("edit_media_types_window", "Alt+C"))
        self.btn_delete_type.setText(_translate("edit_media_types_window", "D&elete"))
        self.lbl_type_name.setText(_translate("edit_media_types_window", "Media Type Name"))
        self.btn_add_type.setText(_translate("edit_media_types_window", "&Add"))
        self.btn_add_type.setShortcut(_translate("edit_media_types_window", "Alt+A"))
        self.lst_media_types.setSortingEnabled(True)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    edit_media_types_window = QtWidgets.QMainWindow()
    ui = Ui_edit_media_types_window()
    ui.setupUi(edit_media_types_window)
    edit_media_types_window.show()
    sys.exit(app.exec_())

